// Unified runtime for 《第七频率》
// This is the single supported game engine used by game.jsp.
const Storage={get:(k,def)=>{try{return JSON.parse(localStorage.getItem('sf_'+k))??def}catch(e){return def}},set:(k,v)=>localStorage.setItem('sf_'+k,JSON.stringify(v))}
const canvas=document.getElementById('gameCanvas')
const ctx=canvas.getContext('2d')
let canvasW,canvasH
const BGM_OUTPUT_GAIN=.45
const MAX_DIALOGUE_FONT_SCALE=320
const defaultSettings={bgmVolume:22,typingSpeed:40,fontScale:100,autoDelay:2000,muteBgm:false,reduceEffects:false}
function clamp(value,min,max){return Math.max(min,Math.min(max,Number(value)||0))}
function loadSettings(){const saved=Storage.get('settings',{});return {...defaultSettings,...saved,bgmVolume:clamp(saved.bgmVolume??defaultSettings.bgmVolume,0,100),typingSpeed:clamp(saved.typingSpeed??defaultSettings.typingSpeed,8,80),fontScale:clamp(saved.fontScale??defaultSettings.fontScale,80,MAX_DIALOGUE_FONT_SCALE),autoDelay:clamp(saved.autoDelay??defaultSettings.autoDelay,800,5000),muteBgm:Boolean(saved.muteBgm),reduceEffects:Boolean(saved.reduceEffects)}}
let settings=loadSettings()
const state={chapter:1,scene:0,dialogueIndex:0,isTyping:false,autoMode:false,skipMode:false,history:[],params:{INTEL:0,DRAMA:0,ACTION:0,TECH:0,CLUE:0,ZHOU:0},affection:{lin_ruolan:30,chen_zixuan:30,gu_laosan:30,xiao_cui:30,bai_jinshu:30},flags:{},sceneData:null,bgImage:null,typingSpeed:settings.typingSpeed,typingTimer:null}
let scriptData=null;let echoes=[]
const MENU_URL='../index.html'
const el={canvasLayer:document.getElementById('canvasLayer'),sceneLoader:document.getElementById('sceneLoader'),speakerName:document.getElementById('speakerName'),dialogueText:document.getElementById('dialogueText'),nextIndicator:document.getElementById('nextIndicator'),choicesLayer:document.getElementById('choicesLayer'),characterLayer:document.getElementById('characterLayer'),illustrationLayer:document.getElementById('illustrationLayer'),illustrationImg:document.getElementById('illustrationImg'),illustCaption:document.getElementById('illustCaption'),dialogueLayer:document.getElementById('dialogueLayer'),dialogueBox:document.getElementById('dialogueBox'),chapterEnd:document.getElementById('chapterEnd'),chapterEndTitle:document.getElementById('chapterEndTitle'),chapterEndSub:document.querySelector('.chapter-end-sub'),nextChapterBtn:document.getElementById('nextChapterBtn'),glitchOverlay:document.getElementById('glitchOverlay'),transitionOverlay:document.getElementById('transitionOverlay'),transitionText:document.getElementById('transitionText'),saveLoadTitle:document.getElementById('saveLoadTitle'),saveLoadModal:document.getElementById('saveLoadModal'),slotsGrid:document.getElementById('slotsGrid'),historyContent:document.getElementById('historyContent'),historyModal:document.getElementById('historyModal'),hudKicker:document.getElementById('hudKicker'),hudTitle:document.getElementById('hudTitle'),hudTime:document.getElementById('hudTime'),hudLocation:document.getElementById('hudLocation'),hudObjective:document.getElementById('hudObjective'),signalGrid:document.getElementById('signalGrid'),signalStrength:document.getElementById('signalStrength'),chapterCard:document.getElementById('chapterCard'),chapterCardKicker:document.getElementById('chapterCardKicker'),chapterCardTitle:document.getElementById('chapterCardTitle'),chapterCardLine:document.getElementById('chapterCardLine'),storyToast:document.getElementById('storyToast'),settingsModal:document.getElementById('settingsModal'),bgmVolume:document.getElementById('bgmVolume'),bgmVolumeValue:document.getElementById('bgmVolumeValue'),typingSpeedInput:document.getElementById('typingSpeed'),typingSpeedValue:document.getElementById('typingSpeedValue'),fontScale:document.getElementById('fontScale'),fontScaleValue:document.getElementById('fontScaleValue'),autoDelay:document.getElementById('autoDelay'),autoDelayValue:document.getElementById('autoDelayValue'),muteBgm:document.getElementById('muteBgm'),reduceEffects:document.getElementById('reduceEffects'),btnSettings:document.getElementById('btnSettings'),closeSettings:document.getElementById('closeSettings'),resetSettings:document.getElementById('resetSettings'),applySettings:document.getElementById('applySettings')}
const chapterBriefs={
  "ch1": "尸体、唱片和第七频率第一次落到沈默手里，死者开始像无线电一样回放。",
  "ch2": "阁楼里的唱片把线索推向亚美公司，所有证据都带着静电噪声。",
  "ch3": "实验室的幽灵终于开口，幸存者和背叛者都被同一段频率牵引。",
  "ch4": "博览会亮起灯牌，上海最体面的舞台下正在准备一场集体失控。",
  "ch5": "假死、真生、记忆共振。最后的选择不只决定谁活下来，也决定谁被记住。"
}
const paramLabels={INTEL:'推理',DRAMA:'人心',ACTION:'行动',TECH:'技术',CLUE:'线索',ZHOU:'弦外'}
const affectionLabels={lin_ruolan:'若兰',chen_zixuan:'子轩',gu_laosan:'老三',xiao_cui:'小翠',bai_jinshu:'白锦书'}
const bgCache=new Map()
const signalKeys=['INTEL','DRAMA','ACTION','TECH','CLUE','ZHOU']
let chapterMap=new Map(),resizeFrame=0,lastDpr=0,glitchTimer=0,signalMeters=null
function resizeCanvas(){const c=el.canvasLayer;const dpr=window.devicePixelRatio||1;const w=c.clientWidth;const h=c.clientHeight;if(w===canvasW&&h===canvasH&&dpr===lastDpr)return;canvasW=w;canvasH=h;lastDpr=dpr;canvas.width=Math.max(1,Math.floor(canvasW*dpr));canvas.height=Math.max(1,Math.floor(canvasH*dpr));canvas.style.width=canvasW+'px';canvas.style.height=canvasH+'px';ctx.setTransform(dpr,0,0,dpr,0,0);if(state.bgImage)drawBackground()}
function scheduleResize(){if(resizeFrame)return;resizeFrame=requestAnimationFrame(()=>{resizeFrame=0;resizeCanvas()})}
resizeCanvas();window.addEventListener('resize',scheduleResize,{passive:true})
async function loadScript(){try{const res=await fetch('../data/script.json');if(!res.ok)throw new Error('HTTP '+res.status+' '+res.statusText);scriptData=await res.json();echoes=scriptData.echoes||[];chapterMap=new Map(scriptData.chapters.map(ch=>[ch.id,ch]));initGame()}catch(e){console.error('加载剧本失败:',e);if(el.sceneLoader)el.sceneLoader.classList.add('hidden');el.speakerName.style.display='none';el.dialogueText.textContent='剧本加载失败，请确认 data/script.json 已部署并刷新页面。'}}
function initGame(){const url=new URL(window.location.href);if(url.searchParams.get('chapter')==='continue'){restoreProgress({chapter:Storage.get('current_chapter',1),scene:Storage.get('current_scene',0),dialogueIndex:Storage.get('current_dialogue',0),params:Storage.get('params',state.params),affection:Storage.get('affection',state.affection),flags:Storage.get('flags',{}),history:Storage.get('history',[])})}else{state.chapter=parseInt(url.searchParams.get('chapter'))||1;state.scene=0;state.dialogueIndex=0}loadScene(state.chapter,state.scene,{dialogueIndex:state.dialogueIndex})}
function clampSceneIndex(chapter,sceneIndex){return Math.max(0,parseInt(sceneIndex)||0)}
function clampDialogueIndex(chapter,sceneIndex,dialogueIndex){const dialogues=chapterMap.get('ch'+chapter)?.scenes?.[sceneIndex]?.dialogues||[];return clamp(dialogueIndex,0,dialogues.length)}
function restoreProgress(data={}){const chapter=parseInt(data.chapter)||1;const scene=clampSceneIndex(chapter,data.scene);state.chapter=chapter;state.scene=scene;state.dialogueIndex=clampDialogueIndex(chapter,scene,data.dialogueIndex);state.params={...state.params,...(data.params||{})};state.affection={...state.affection,...(data.affection||{})};state.flags={...(data.flags||{})};state.history=Array.isArray(data.history)?[...data.history]:[]}
function snapshotProgress(){return{chapter:state.chapter,scene:state.scene,dialogueIndex:state.dialogueIndex,params:{...state.params},affection:{...state.affection},flags:{...state.flags},history:[...state.history]}}
function goToScene(chapter,sceneIndex,dialogueIndex=0){state.chapter=parseInt(chapter)||state.chapter;state.scene=clampSceneIndex(state.chapter,sceneIndex);state.dialogueIndex=clampDialogueIndex(state.chapter,state.scene,dialogueIndex);saveProgress();return loadScene(state.chapter,state.scene,{dialogueIndex:state.dialogueIndex})}
async function loadScene(chapter,sceneIndex,options={}){state.chapter=parseInt(chapter)||state.chapter;state.scene=clampSceneIndex(state.chapter,sceneIndex);el.sceneLoader.classList.remove('hidden');hideChoices();closeIllustration();const chData=chapterMap.get('ch'+state.chapter);if(!chData||!chData.scenes[state.scene]){showChapterEnd();el.sceneLoader.classList.add('hidden');return}state.sceneData=chData.scenes[state.scene];state.dialogueIndex=clampDialogueIndex(state.chapter,state.scene,options.dialogueIndex??0);state.isTyping=false;clearTimeout(state.typingTimer);if(state.sceneData.bg){state.bgImage=await loadBackground(state.sceneData.bg);drawBackground()}else{state.bgImage=null;drawBackground()}playBGM(state.sceneData.bgm);preloadUpcomingScene(chData,state.scene);renderSceneChrome(chData,state.sceneData);showSceneCard(chData,state.sceneData);checkEchoes();updateSignalPanel();el.sceneLoader.classList.add('hidden');renderDialogue();if(isFrequencyScene(state.sceneData))setTimeout(()=>triggerGlitch(10,420),520)}
function assetPath(src,folder){return src.startsWith('assets/')?'../'+src:'../assets/'+folder+'/'+src}
function loadBackground(src){const path=assetPath(src,'bg');if(bgCache.has(path))return bgCache.get(path);const promise=new Promise(resolve=>{const img=new Image();img.decoding='async';img.onload=()=>resolve(img);img.onerror=()=>{console.warn('BG load failed:',src);resolve(null)};img.src=path});bgCache.set(path,promise);return promise}
function preloadUpcomingScene(chData,sceneIndex){const next=chData.scenes[sceneIndex+1];if(next?.bg)loadBackground(next.bg)}
function drawBackground(){ctx.fillStyle='#1a1510';ctx.fillRect(0,0,canvasW,canvasH);if(state.bgImage){const ratio=Math.max(canvasW/state.bgImage.width,canvasH/state.bgImage.height);ctx.drawImage(state.bgImage,(canvasW-state.bgImage.width*ratio)/2,(canvasH-state.bgImage.height*ratio)/2,state.bgImage.width*ratio,state.bgImage.height*ratio)}ctx.fillStyle='rgba(196,167,125,0.08)';ctx.fillRect(0,0,canvasW,canvasH)}
function sceneHasConditionalChoice(scene){return (scene?.choices||[]).some(choice=>choice.condition||choice.special)}
function firstNarration(scene){return (scene?.dialogues||[]).find(d=>!d.speaker&&d.text)?.text||(scene?.dialogues||[])[0]?.text||''}
function getSceneBrief(chData,scene){const first=firstNarration(scene).replace(/\s+/g,'');const line=(state.scene===0?(chData.title+'开场。'):'')+(first?first.slice(0,54)+(first.length>54?'...':''):(chapterBriefs[chData.id]||''));const choiceCount=(scene?.choices||[]).length;return{time:scene?.time||chData?.date||'1931',location:scene?.location||chData?.location||'上海',objective:sceneHasConditionalChoice(scene)?('推进「'+(scene?.title||chData.title)+'」并留意条件选项的回响。'):(choiceCount>3?('在「'+(scene?.title||chData.title)+'」中做出关键判断，改写后续案卷。'):('跟进「'+(scene?.title||chData.title)+'」的线索，让第七频率继续显影。')),line}}
function isFrequencyScene(scene){return scene?.id==='ch4_sc5'}
function isKeyChoice(choice){const effects={...(choice.effects||{}),...(choice.affection||{})};return Boolean(choice.flag||choice.nextScene?.startsWith('ch5_')||Object.entries(effects).some(([key,val])=>Math.abs(Number(val)||0)>=15||key==='CLUE'))}
function renderSceneChrome(chData,scene){const brief=getSceneBrief(chData,scene);el.hudKicker.textContent='案卷 '+chData.id.toUpperCase()+' / '+String(state.scene+1).padStart(2,'0');el.hudTitle.textContent=scene.title||chData.title;el.hudTime.textContent=brief.time||'1931';el.hudLocation.textContent=brief.location||'上海';el.hudObjective.textContent=brief.objective||chapterBriefs[chData.id]||'追踪第七频率的下一段回声'}
function showSceneCard(chData,scene){const brief=getSceneBrief(chData,scene);el.chapterCardKicker.textContent=state.scene===0?'CHAPTER '+state.chapter:'SCENE '+String(state.scene+1).padStart(2,'0');el.chapterCardTitle.textContent=scene.title||chData.title;el.chapterCardLine.textContent=brief.line||chapterBriefs[chData.id]||'';el.chapterCard.classList.add('active');clearTimeout(showSceneCard.timer);showSceneCard.timer=setTimeout(()=>el.chapterCard.classList.remove('active'),state.scene===0?2200:1600)}
function renderSettingsControls(){if(!el.bgmVolume)return;el.bgmVolume.value=settings.bgmVolume;el.bgmVolumeValue.textContent=settings.bgmVolume+'%';el.typingSpeedInput.value=settings.typingSpeed;el.typingSpeedValue.textContent=settings.typingSpeed+'ms';if(el.fontScale){el.fontScale.value=Math.min(Number(el.fontScale.max)||260,settings.fontScale);el.fontScaleValue.textContent=settings.fontScale+'%'}el.autoDelay.value=settings.autoDelay;el.autoDelayValue.textContent=(settings.autoDelay/1000).toFixed(1)+'s';el.muteBgm.checked=settings.muteBgm;el.reduceEffects.checked=settings.reduceEffects}
function applyGameSettings(nextSettings,save=true){settings=loadSettings();settings={...settings,...nextSettings,bgmVolume:clamp(nextSettings.bgmVolume??settings.bgmVolume,0,100),typingSpeed:clamp(nextSettings.typingSpeed??settings.typingSpeed,8,80),fontScale:clamp(nextSettings.fontScale??settings.fontScale,80,MAX_DIALOGUE_FONT_SCALE),autoDelay:clamp(nextSettings.autoDelay??settings.autoDelay,800,5000),muteBgm:Boolean(nextSettings.muteBgm??settings.muteBgm),reduceEffects:Boolean(nextSettings.reduceEffects??settings.reduceEffects)};state.typingSpeed=settings.typingSpeed;document.documentElement.style.setProperty('--dialogue-font-scale',(settings.fontScale/100).toFixed(2));document.body.classList.toggle('reduce-effects',settings.reduceEffects);if(bgmAudio)bgmAudio.volume=getBgmVolume();if(save)Storage.set('settings',settings);renderSettingsControls()}
function openSettings(){renderSettingsControls();el.settingsModal.classList.add('active');hideDialogue()}
function closeSettings(){el.settingsModal.classList.remove('active');showDialogue()}
function initSignalPanel(){if(signalMeters)return;signalMeters={};const fragment=document.createDocumentFragment();signalKeys.forEach(key=>{const row=document.createElement('div');row.className='signal-row';const label=document.createElement('span');label.textContent=paramLabels[key];const track=document.createElement('span');track.className='signal-track';const fill=document.createElement('span');fill.className='signal-fill';const value=document.createElement('span');track.appendChild(fill);row.append(label,track,value);fragment.appendChild(row);signalMeters[key]={fill,value}});el.signalGrid.textContent='';el.signalGrid.appendChild(fragment)}
function updateSignalPanel(){initSignalPanel();const total=signalKeys.reduce((sum,key)=>sum+Math.max(0,state.params[key]||0),0);el.signalStrength.textContent=String(Math.min(99,total)).padStart(2,'0');signalKeys.forEach(key=>{const val=state.params[key]||0;signalMeters[key].fill.style.width=Math.min(100,Math.max(0,val*4))+'%';signalMeters[key].value.textContent=String(val)})}
function conditionMet(condition){if(!condition)return true;if(condition.flag&&!state.flags[condition.flag])return false;if(condition.flags&&condition.flags.some(flag=>!state.flags[flag]))return false;if(condition.params){for(const[key,rule]of Object.entries(condition.params)){const val=state.params[key]||0;if(typeof rule==='number'&&val<rule)return false;if(rule.min!==undefined&&val<rule.min)return false;if(rule.max!==undefined&&val>rule.max)return false}}if(condition.affection){for(const[key,rule]of Object.entries(condition.affection)){const val=state.affection[key]||0;if(typeof rule==='number'&&val<rule)return false;if(rule.min!==undefined&&val<rule.min)return false;if(rule.max!==undefined&&val>rule.max)return false}}return true}
function visibleChoices(choices){return (choices||[]).filter(choice=>conditionMet(choice.condition))}
function formatEffectChips(choice){const chips=[];if(choice.special)chips.push('特殊');if(choice.condition)chips.push('条件达成');const collect=obj=>{if(!obj)return;Object.entries(obj).forEach(([key,val])=>{const delta=Number(val)||0;if(!delta)return;const label=paramLabels[key]||affectionLabels[key]||key;chips.push(label+(delta>0?' +':' ')+delta)})};collect(choice.effects);collect(choice.affection);if(choice.flag)chips.push('标记入档');return chips}
function showToast(title,body,tone='default',detail=''){if(!el.storyToast)return;const card=document.createElement('div');card.className='toast-card tone-'+tone;const head=document.createElement('div');head.className='toast-title';head.textContent=title;const text=document.createElement('div');text.className='toast-body';text.textContent=body;if(detail){const meta=document.createElement('div');meta.className='toast-detail';meta.textContent=detail;card.append(head,text,meta)}else{card.append(head,text)}el.storyToast.appendChild(card);setTimeout(()=>card.remove(),4400)}
function showChoiceFeedback(choice,summary){const fb=choice.feedback||{};const title=fb.title||'决策反馈';const body=fb.body||'选择已经写入案卷，后续分支会记住这次判断。';const detail=fb.detail||summary.join(' · ');showToast(title,body,fb.tone||'default',detail);state.history.push({type:'feedback',chapter:state.chapter,scene:state.scene,title,body,detail})}function playSpecialTransition(text,onComplete,options={}){if(!el.transitionOverlay||!el.transitionText){if(onComplete)onComplete();return}el.sceneLoader.classList.remove('hidden');el.transitionOverlay.classList.add('active');el.transitionText.textContent='';let i=0;const baseSpeed=state.skipMode?8:28;const speed=options.typeSpeed||baseSpeed;const holdMs=options.holdMs||2200;const fadeMs=options.fadeMs||900;function type(){if(i<text.length){el.transitionText.textContent+=text.charAt(i);i++;setTimeout(type,speed)}else{setTimeout(()=>{el.transitionOverlay.classList.remove('active');setTimeout(()=>{el.transitionText.textContent='';el.sceneLoader.classList.add('hidden');if(onComplete)onComplete()},fadeMs)},holdMs)}}setTimeout(type,400)}
function renderDialogue(){const scene=state.sceneData;if(!scene||state.dialogueIndex>=scene.dialogues.length){const choices=visibleChoices(scene?.choices);if(choices.length>0){showChoices(choices)}else{nextScene()}return}const dia=scene.dialogues[state.dialogueIndex];el.speakerName.textContent=dia.speaker||'';el.speakerName.style.display=dia.speaker?'block':'none';el.nextIndicator.style.opacity='0';if(dia.illustration)showIllustration(dia.illustration,dia.text,{durationMs:dia.illustrationDuration});updateCharacter(dia.speaker,dia.expression);typewriter(dia.text,el.dialogueText,()=>{state.isTyping=false;el.nextIndicator.style.opacity='1';state.history.push({speaker:dia.speaker,text:dia.text});if(state.autoMode)setTimeout(advanceDialogue,settings.autoDelay);if(state.skipMode)setTimeout(advanceDialogue,200)})}
function typewriter(text,el,callback){state.isTyping=true;el.textContent='';let i=0;const speed=state.skipMode?5:state.typingSpeed;function type(){if(i<text.length){el.textContent+=text.charAt(i);i++;state.typingTimer=setTimeout(type,speed)}else if(callback)callback()}type()}
function advanceDialogue(){if(state.isTyping){clearTimeout(state.typingTimer);const dia=state.sceneData.dialogues[state.dialogueIndex];el.dialogueText.textContent=dia.text;state.isTyping=false;el.nextIndicator.style.opacity='1';state.history.push({speaker:dia.speaker,text:dia.text});saveProgress();return}state.dialogueIndex++;saveProgress();hideChoices();renderDialogue()}
function showChoices(choices){const fragment=document.createDocumentFragment();el.choicesLayer.textContent='';choices.forEach((choice,i)=>{const btn=document.createElement('button');btn.className='choice-btn'+(choice.special?' special-choice':'');btn.dataset.index=i;btn.style.setProperty('--choice-delay',(i*55)+'ms');const label=document.createElement('span');label.className='choice-label';label.textContent=String.fromCharCode(65+i)+'.';const copy=document.createElement('span');copy.className='choice-copy';copy.textContent=choice.text;btn.append(label,copy);const chips=formatEffectChips(choice);if(chips.length){const meta=document.createElement('span');meta.className='choice-meta';chips.forEach(text=>{const chip=document.createElement('span');chip.className='choice-chip';chip.textContent=text;meta.appendChild(chip)});btn.appendChild(meta)}btn.addEventListener('click',()=>makeChoice(choice));fragment.appendChild(btn)});el.choicesLayer.appendChild(fragment);el.choicesLayer.classList.add('active')}
function hideChoices(){el.choicesLayer.classList.remove('active')}
function makeChoice(choice){const feedback=[];let clueGain=0;const keyChoice=isKeyChoice(choice);if(choice.effects!=null&&typeof choice.effects==='object'){for(let[key,val]of Object.entries(choice.effects)){const delta=Number(val)||0;if(state.params[key]!==undefined){state.params[key]=Math.max(-100,Math.min(100,state.params[key]+delta));feedback.push((paramLabels[key]||key)+(delta>0?' +':' ')+delta);if(key==='CLUE'&&delta>0)clueGain+=delta}else if(state.affection[key]!==undefined){state.affection[key]=Math.max(0,Math.min(100,state.affection[key]+delta));feedback.push((affectionLabels[key]||key)+(delta>0?' +':' ')+delta)}}}if(choice.affection){for(let[key,val]of Object.entries(choice.affection)){const delta=Number(val)||0;if(state.affection[key]!==undefined){state.affection[key]=Math.max(0,Math.min(100,state.affection[key]+delta));feedback.push((affectionLabels[key]||key)+(delta>0?' +':' ')+delta)}}}if(choice.flag){state.flags[choice.flag]=true;feedback.push('新标记 '+choice.flag)}state.history.push({type:'choice',chapter:state.chapter,scene:state.scene,choice:choice.id,text:choice.text});hideChoices();updateSignalPanel();function doTransition(){showChoiceFeedback(choice,feedback);if(clueGain>0)showToast('线索入档','案卷新增 '+clueGain+' 条可用线索，后续分支会记住这次判断。','clue');if(choice.special)triggerGlitch(9,340);else if(keyChoice)triggerGlitch(clueGain>0?7:5,260);const nextCh=parseInt(choice.nextScene?.match(/ch(\d+)/)?.[1]);if(nextCh&&nextCh>state.chapter){const unlocked=Storage.get('unlocked_chapters',[1]);if(!unlocked.includes(nextCh)){unlocked.push(nextCh);Storage.set('unlocked_chapters',unlocked)}}if(choice.nextScene){const match=choice.nextScene.match(/ch(\d+)_sc(\d+)/);if(match){goToScene(parseInt(match[1]),parseInt(match[2])-1,0)}else{nextScene()}}else{nextScene()}}if(choice.transition){playSpecialTransition(choice.transition,doTransition,{holdMs:choice.transitionDuration,typeSpeed:choice.transitionSpeed})}else{doTransition()}}
function nextScene(){goToScene(state.chapter,state.scene+1,0)}
function updateCharacter(speaker,expression){el.characterLayer.innerHTML='';if(!speaker)return;const charMap={'沈默':'shenmo','林若兰':'linruolan','陈子轩':'chenzixuan','顾老三':'gulaosan','小翠':'xiaocui','白锦书':'baijinshu','陶启明':'taoqiming','灰西装男人':'taoqiming','周老板':'zhoulaoban','未知声音':null,'安徽帮头目':null,'帮派头目':null,'时间':null,'陈子轩 + 林若兰':null,'男尸':null,'白若雪':null};const charExpressions={shenmo:['neutral','thinking'],linruolan:['neutral','smile'],chenzixuan:['neutral','thinking'],gulaosan:['neutral','smile'],xiaocui:['neutral','smile'],baijinshu:['neutral','angry'],taoqiming:['neutral','thinking'],zhoulaoban:['neutral','thinking']};const charId=charMap[speaker];if(!charId)return;const allowed=charExpressions[charId]||['neutral'];const expr=allowed.includes(expression)?expression:'neutral';const img=document.createElement('img');img.className='character-sprite center active breathing';img.alt=speaker;img.onerror=()=>img.remove();img.src='../assets/characters/'+charId+'_'+expr+'.png';el.characterLayer.appendChild(img)}
function unlockIllustration(src){const path=assetPath(src,'illustrations');const unlocked=Storage.get('unlocked_illustrations',[]);if(!unlocked.includes(path)){unlocked.push(path);Storage.set('unlocked_illustrations',unlocked)}}
function closeIllustration(){el.illustrationLayer.classList.remove('active');el.dialogueLayer.style.display=''}
function showIllustration(src,caption,options={}){const imgPath=assetPath(src,'illustrations');unlockIllustration(src);el.illustrationImg.src=imgPath;el.illustCaption.textContent=caption||'';el.illustrationLayer.classList.remove('active');void el.illustrationLayer.offsetWidth;el.illustrationLayer.classList.add('active');el.dialogueLayer.style.display='none';const durationMs=options.durationMs||7000;setTimeout(()=>{closeIllustration();if(state.autoMode)setTimeout(advanceDialogue,settings.autoDelay)},durationMs)}
document.getElementById('illustClose').addEventListener('click',closeIllustration)
function checkEchoes(){echoes.filter(e=>e.chapter===state.chapter&&(e.scene===state.scene||e.scene===state.scene+1)&&(!e.condition||state.flags[e.condition.flag]===true)).forEach(echo=>showEchoRipple(echo))}
function showEchoRipple(echo){const ripple=document.createElement('div');ripple.className='echo-ripple';ripple.style.left=(canvasW/2-10)+'px';ripple.style.top=(canvasH/2-10)+'px';el.canvasLayer.appendChild(ripple);setTimeout(()=>ripple.remove(),2000);el.dialogueBox.classList.add('echo-lit');setTimeout(()=>el.dialogueBox.classList.remove('echo-lit'),1500);triggerGlitch(8,320);showToast('回响捕获',echo.title||echo.message||echo.text||'第七频率短暂穿透了当前场景。')}
function triggerGlitch(intensity=5,duration=220){if(settings.reduceEffects)return;el.glitchOverlay.textContent='';const fragment=document.createDocumentFragment();for(let i=0;i<intensity;i++){const strip=document.createElement('div');strip.className='glitch-strip';strip.style.top=Math.random()*100+'%';strip.style.height=(2+Math.random()*6)+'px';strip.style.background=Math.random()>0.5?'var(--neon-cyan)':'var(--neon-purple)';fragment.appendChild(strip)}el.glitchOverlay.appendChild(fragment);el.glitchOverlay.classList.add('active');clearTimeout(glitchTimer);glitchTimer=setTimeout(()=>el.glitchOverlay.classList.remove('active'),duration)}
function showChapterEnd(){stopBGM();const chData=chapterMap.get('ch'+state.chapter);el.chapterEndTitle.textContent=chData?'— '+chData.title+' 完 —':'— 章节完成 —';if(el.chapterEndSub)el.chapterEndSub.textContent=chData?(chapterBriefs[chData.id]||'你的选择已经写入案卷。'):'你的选择已经写入案卷。';el.nextChapterBtn.textContent=state.chapter>=scriptData.chapters.length?'返回主菜单':'继续';el.chapterEnd.classList.add('active')}
el.nextChapterBtn.addEventListener('click',()=>{el.chapterEnd.classList.remove('active');const next=state.chapter+1;const unlocked=Storage.get('unlocked_chapters',[1]);if(next<=scriptData.chapters.length&&!unlocked.includes(next)){unlocked.push(next);Storage.set('unlocked_chapters',unlocked)}window.location.href=MENU_URL})
function saveProgress(){Storage.set('current_chapter',state.chapter);Storage.set('current_scene',state.scene);Storage.set('current_dialogue',state.dialogueIndex);Storage.set('params',state.params);Storage.set('affection',state.affection);Storage.set('flags',state.flags);Storage.set('history',state.history)}

// === BGM 播放 ===
let bgmAudio=null;let pendingBgmPath=null;let currentBgmPath=null;
function syncBgmSettings(){settings=loadSettings();state.typingSpeed=settings.typingSpeed;document.documentElement.style.setProperty('--dialogue-font-scale',(settings.fontScale/100).toFixed(2));renderSettingsControls()}
function getBgmVolume(){return settings.muteBgm?0:Math.min(1,settings.bgmVolume/100*BGM_OUTPUT_GAIN)}
function playBGM(src){syncBgmSettings();const path=src?(src.startsWith('assets/')?'../'+src:'../assets/audio/'+src):null;if(path===currentBgmPath){if(bgmAudio)bgmAudio.volume=getBgmVolume();return}if(bgmAudio){bgmAudio.pause();bgmAudio=null}currentBgmPath=path;pendingBgmPath=null;if(!path)return;bgmAudio=new Audio(path);bgmAudio.loop=true;bgmAudio.volume=getBgmVolume();bgmAudio.play().catch(()=>{pendingBgmPath=path;console.warn('BGM autoplay blocked, waiting for user gesture')})}
function stopBGM(){if(bgmAudio){bgmAudio.pause();bgmAudio=null}pendingBgmPath=null;currentBgmPath=null}
function unlockBGM(){if(!pendingBgmPath)return;const path=pendingBgmPath;pendingBgmPath=null;if(!bgmAudio||currentBgmPath!==path){bgmAudio=new Audio(path);bgmAudio.loop=true;currentBgmPath=path}bgmAudio.volume=getBgmVolume();bgmAudio.play().catch(()=>pendingBgmPath=path)}
applyGameSettings(settings,false)
if(el.settingsModal&&el.settingsModal.parentElement!==document.body)document.body.appendChild(el.settingsModal)
document.addEventListener('pointerdown',unlockBGM)
el.dialogueBox.addEventListener('click',advanceDialogue)
const controls={save:document.getElementById('btnSave'),load:document.getElementById('btnLoad'),history:document.getElementById('btnHistory'),auto:document.getElementById('btnAuto'),skip:document.getElementById('btnSkip'),back:document.getElementById('btnBack')}
function setModeButtonState(){controls.auto.classList.toggle('is-active',state.autoMode);controls.skip.classList.toggle('is-active',state.skipMode);controls.auto.setAttribute('aria-pressed',String(state.autoMode));controls.skip.setAttribute('aria-pressed',String(state.skipMode))}
function hideDialogue(){el.dialogueLayer.style.display='none'}
function showDialogue(){el.dialogueLayer.style.display=''}
function openSaveLoad(mode){el.saveLoadTitle.textContent=mode==='save'?'\u2014 \u5b58\u6863 \u2014':'\u2014 \u8bfb\u6863 \u2014';renderSlots(mode);el.saveLoadModal.classList.add('active');hideDialogue()}
function openHistory(){el.historyContent.textContent='';const items=state.history.slice(-40);if(!items.length){const empty=document.createElement('div');empty.className='history-empty';empty.textContent='\u6682\u65e0\u5386\u53f2\u8bb0\u5f55';el.historyContent.appendChild(empty)}items.forEach(h=>{const entry=document.createElement('div');entry.className='history-entry';if(h.type==='choice'){entry.classList.add('choice-history');entry.textContent='\u25c6 \u9009\u62e9: '+h.text}else if(h.type==='feedback'){entry.classList.add('feedback-history');entry.textContent='↳ '+h.title+'：'+h.body+(h.detail?' ['+h.detail+']':'')}else{const speaker=document.createElement('span');speaker.className='history-speaker';speaker.textContent=(h.speaker||'\u65c1\u767d')+':';entry.append(speaker,document.createTextNode(h.text))}el.historyContent.appendChild(entry)});el.historyModal.classList.add('active');hideDialogue()}
function modalIsActive(){return el.settingsModal.classList.contains('active')||el.saveLoadModal.classList.contains('active')||el.historyModal.classList.contains('active')}
function closeTopModal(){if(el.settingsModal.classList.contains('active')){closeSettings();return true}if(el.saveLoadModal.classList.contains('active')){el.saveLoadModal.classList.remove('active');showDialogue();return true}if(el.historyModal.classList.contains('active')){el.historyModal.classList.remove('active');showDialogue();return true}return false}
function shortcutBlocked(target){const tag=target?.tagName?.toLowerCase();return target?.isContentEditable||['input','textarea','select'].includes(tag)}
function handleGlobalShortcuts(e){if(e.defaultPrevented)return;const key=e.key.toLowerCase();if(key==='escape'){e.preventDefault();if(!closeTopModal())controls.back.click();return}if(modalIsActive()||shortcutBlocked(e.target))return;if((e.ctrlKey||e.metaKey)&&key==='s'){e.preventDefault();openSaveLoad('save');return}if((e.ctrlKey||e.metaKey)&&key==='l'){e.preventDefault();openSaveLoad('load');return}if(e.ctrlKey||e.metaKey||e.altKey)return;if(key==='h'){e.preventDefault();openHistory();return}if(key==='a'){e.preventDefault();controls.auto.click();return}if(key==='k'){e.preventDefault();controls.skip.click()}}
controls.auto.addEventListener('click',()=>{state.autoMode=!state.autoMode;state.skipMode=false;setModeButtonState();if(state.autoMode&&!state.isTyping)setTimeout(advanceDialogue,settings.autoDelay)})
controls.skip.addEventListener('click',()=>{state.skipMode=!state.skipMode;state.autoMode=false;setModeButtonState()})
controls.save.addEventListener('click',()=>openSaveLoad('save'))
controls.load.addEventListener('click',()=>openSaveLoad('load'))
document.getElementById('closeSaveLoad').addEventListener('click',()=>{el.saveLoadModal.classList.remove('active');showDialogue()})
controls.history.addEventListener('click',openHistory)
document.getElementById('closeHistory').addEventListener('click',()=>{el.historyModal.classList.remove('active');showDialogue()})
controls.back.addEventListener('click',()=>{if(confirm('返回主菜单？当前进度已自动保存。'))window.location.href=MENU_URL})
el.btnSettings.addEventListener('click',openSettings)
el.closeSettings.addEventListener('click',closeSettings)
el.applySettings.addEventListener('click',closeSettings)
el.settingsModal.addEventListener('click',e=>{if(e.target===el.settingsModal)closeSettings()})
el.bgmVolume.addEventListener('input',()=>applyGameSettings({bgmVolume:Number(el.bgmVolume.value)}))
el.typingSpeedInput.addEventListener('input',()=>applyGameSettings({typingSpeed:Number(el.typingSpeedInput.value)}))
if(el.fontScale)el.fontScale.addEventListener('input',()=>applyGameSettings({fontScale:Number(el.fontScale.value)}))
el.autoDelay.addEventListener('input',()=>applyGameSettings({autoDelay:Number(el.autoDelay.value)}))
el.muteBgm.addEventListener('change',()=>applyGameSettings({muteBgm:el.muteBgm.checked}))
el.reduceEffects.addEventListener('change',()=>applyGameSettings({reduceEffects:el.reduceEffects.checked}))
el.resetSettings.addEventListener('click',()=>applyGameSettings(defaultSettings))
document.addEventListener('keydown',handleGlobalShortcuts)
function formatSaveTime(timestamp){if(!timestamp)return '\u65e0\u65f6\u95f4\u8bb0\u5f55';const date=new Date(timestamp);if(Number.isNaN(date.getTime()))return '\u65e0\u65f6\u95f4\u8bb0\u5f55';const pad=n=>String(n).padStart(2,'0');const now=new Date();const sameDay=date.getFullYear()===now.getFullYear()&&date.getMonth()===now.getMonth()&&date.getDate()===now.getDate();return (sameDay?'\u4eca\u65e5 ':`${date.getMonth()+1}/${date.getDate()} `)+pad(date.getHours())+':'+pad(date.getMinutes())}
function createSlotMeta(className,text){const node=document.createElement('div');node.className=className;node.textContent=text;return node}
function renderSlots(mode){el.slotsGrid.textContent='';const fragment=document.createDocumentFragment();for(let i=1;i<=9;i++){const data=Storage.get('save_slot_'+i,null);const btn=document.createElement('button');btn.type='button';btn.className='slot-btn'+(data?' has-data':'');btn.appendChild(createSlotMeta('slot-number',String(i)));if(data){btn.appendChild(createSlotMeta('slot-scene','Ch'+data.chapter+' Sc'+(data.scene+1)));btn.appendChild(createSlotMeta('slot-time',formatSaveTime(data.timestamp)));btn.appendChild(createSlotMeta('slot-action',mode==='save'?'\u8986\u76d6\u6b64\u6863':'\u8bfb\u53d6\u8fdb\u5ea6'))}else{btn.appendChild(createSlotMeta('slot-scene','\u7a7a\u6863\u4f4d'));btn.appendChild(createSlotMeta('slot-time',mode==='save'?'\u53ef\u5b58\u5165':'\u6682\u65e0\u8bb0\u5f55'));btn.disabled=mode==='load';if(mode==='load')btn.setAttribute('aria-disabled','true')}btn.addEventListener('click',()=>{if(mode==='save'){const saveData={...snapshotProgress(),timestamp:Date.now()};Storage.set('save_slot_'+i,saveData);el.saveLoadModal.classList.remove('active');showToast('\u5df2\u5b58\u6863','Ch'+state.chapter+' Sc'+(state.scene+1)+' \u5df2\u5199\u5165\u6863\u4f4d '+i)}else if(data){restoreProgress(data);el.saveLoadModal.classList.remove('active');saveProgress();loadScene(state.chapter,state.scene,{dialogueIndex:state.dialogueIndex})}});fragment.appendChild(btn)}el.slotsGrid.appendChild(fragment)}
window.SeventhFrequencyEngine={state,Storage,loadScene,nextScene,advanceDialogue,makeChoice,saveProgress,playBGM,stopBGM,applyGameSettings,getBgmVolume,get settings(){return settings},get script(){return scriptData},get echoes(){return echoes}};
setModeButtonState()
window.engine={pause:function(){state.autoMode=false;state.skipMode=false;setModeButtonState();},resume:function(){},click:function(){advanceDialogue();},state,loadScene};
loadScript()
